// Generated by Haxe 3.4.7
#ifndef INCLUDED_Pzd
#define INCLUDED_Pzd

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS0(Pzd)



class HXCPP_CLASS_ATTRIBUTES Pzd_obj : public hx::Object
{
	public:
		typedef hx::Object super;
		typedef Pzd_obj OBJ_;
		Pzd_obj();

	public:
		enum { _hx_ClassId = 0x003d1efa };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="Pzd")
			{ return hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return hx::Object::operator new(inSize+extra,false,"Pzd"); }

		hx::ObjectPtr< Pzd_obj > __new() {
			hx::ObjectPtr< Pzd_obj > __this = new Pzd_obj();
			__this->__construct();
			return __this;
		}

		static hx::ObjectPtr< Pzd_obj > __alloc(hx::Ctx *_hx_ctx) {
			Pzd_obj *__this = (Pzd_obj*)(hx::Ctx::alloc(_hx_ctx, sizeof(Pzd_obj), false, "Pzd"));
			*(void **)__this = Pzd_obj::_hx_vtable;
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(hx::DynamicArray inArgs);
		//~Pzd_obj();

		HX_DO_RTTI_ALL;
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, hx::PropertyAccess inCallProp);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_HCSTRING("Pzd","\xfa","\x1e","\x3d","\x00"); }

		static void main();
		static ::Dynamic main_dyn();

};


#endif /* INCLUDED_Pzd */ 
