// Generated by Haxe 3.4.7
#include <hxcpp.h>

#ifndef INCLUDED_haxe_Log
#include <haxe/Log.h>
#endif
#ifndef INCLUDED_sys_io_Process
#include <sys/io/Process.h>
#endif
#ifndef INCLUDED_haxe_io_Eof
#include <haxe/io/Eof.h>
#endif
#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_ChildProcess
#include <ChildProcess.h>
#endif
#ifndef INCLUDED_Pzd
#include <Pzd.h>
#endif

void __files__boot();

void __boot_all()
{
__files__boot();
hx::RegisterResources( hx::GetResources() );
::haxe::Log_obj::__register();
::sys::io::Process_obj::__register();
::haxe::io::Eof_obj::__register();
::Std_obj::__register();
::ChildProcess_obj::__register();
::Pzd_obj::__register();
::haxe::Log_obj::__boot();
}

