// Generated by Haxe 3.4.7
#include <hxcpp.h>

namespace hx {
const char *__hxcpp_all_files[] = {
#ifdef HXCPP_DEBUGGER
"/usr/local/lib/haxe/std/cpp/_std/Std.hx",
"/usr/local/lib/haxe/std/haxe/Log.hx",
"/usr/local/lib/haxe/std/haxe/io/Eof.hx",
"?",
"Pzd.hx",
#endif
 0 };

const char *__hxcpp_all_files_fullpath[] = {
#ifdef HXCPP_DEBUGGER
"/usr/local/lib/haxe/std/cpp/_std/Std.hx",
"/usr/local/lib/haxe/std/haxe/Log.hx",
"/usr/local/lib/haxe/std/haxe/io/Eof.hx",
"?",
"/Users/frg105/dev/personal/pidzero/pzd.hx",
#endif
 0 };

const char *__hxcpp_all_classes[] = {
#ifdef HXCPP_DEBUGGER
"Pzd",
"ChildProcess",
"Std",
"haxe.Log",
"haxe.io.Eof",
"sys.io.Process",
#endif
 0 };
} // namespace hx
void __files__boot() { __hxcpp_set_debugger_info(hx::__hxcpp_all_classes, hx::__hxcpp_all_files_fullpath); }
