// Generated by Haxe 3.4.7
#include <hxcpp.h>

#ifndef INCLUDED_Pzd
#include <Pzd.h>
#endif
#ifndef INCLUDED_haxe_Log
#include <haxe/Log.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_56307c772d5dc60f_10_main,"Pzd","main",0x71733e2d,"Pzd.main","Pzd.hx",10,0x7dac3c04)

void Pzd_obj::__construct() { }

Dynamic Pzd_obj::__CreateEmpty() { return new Pzd_obj; }

void *Pzd_obj::_hx_vtable = 0;

Dynamic Pzd_obj::__Create(hx::DynamicArray inArgs)
{
	hx::ObjectPtr< Pzd_obj > _hx_result = new Pzd_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool Pzd_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x003d1efa;
}

void Pzd_obj::main(){
            	HX_STACKFRAME(&_hx_pos_56307c772d5dc60f_10_main)
HXDLIN(  10)		::haxe::Log_obj::trace(HX_("**** Start pzd",9c,3d,a2,de),hx::SourceInfo(HX_("Pzd.hx",04,3c,ac,7d),10,HX_("Pzd",fa,1e,3d,00),HX_("main",39,38,56,48)));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC0(Pzd_obj,main,(void))


Pzd_obj::Pzd_obj()
{
}

bool Pzd_obj::__GetStatic(const ::String &inName, Dynamic &outValue, hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"main") ) { outValue = main_dyn(); return true; }
	}
	return false;
}

#if HXCPP_SCRIPTABLE
static hx::StorageInfo *Pzd_obj_sMemberStorageInfo = 0;
static hx::StaticInfo *Pzd_obj_sStaticStorageInfo = 0;
#endif

static void Pzd_obj_sMarkStatics(HX_MARK_PARAMS) {
	HX_MARK_MEMBER_NAME(Pzd_obj::__mClass,"__mClass");
};

#ifdef HXCPP_VISIT_ALLOCS
static void Pzd_obj_sVisitStatics(HX_VISIT_PARAMS) {
	HX_VISIT_MEMBER_NAME(Pzd_obj::__mClass,"__mClass");
};

#endif

hx::Class Pzd_obj::__mClass;

static ::String Pzd_obj_sStaticFields[] = {
	HX_HCSTRING("main","\x39","\x38","\x56","\x48"),
	::String(null())
};

void Pzd_obj::__register()
{
	hx::Object *dummy = new Pzd_obj;
	Pzd_obj::_hx_vtable = *(void **)dummy;
	hx::Static(__mClass) = new hx::Class_obj();
	__mClass->mName = HX_HCSTRING("Pzd","\xfa","\x1e","\x3d","\x00");
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &Pzd_obj::__GetStatic;
	__mClass->mSetStaticField = &hx::Class_obj::SetNoStaticField;
	__mClass->mMarkFunc = Pzd_obj_sMarkStatics;
	__mClass->mStatics = hx::Class_obj::dupFunctions(Pzd_obj_sStaticFields);
	__mClass->mMembers = hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = hx::TCanCast< Pzd_obj >;
#ifdef HXCPP_VISIT_ALLOCS
	__mClass->mVisitFunc = Pzd_obj_sVisitStatics;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = Pzd_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = Pzd_obj_sStaticStorageInfo;
#endif
	hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

